enabled: true
color: blue
dropdown:
  enabled: true
production-mode: true
logo: {  }
hero_title: 'Telephasic is a responsive <br />site template by <a href="http://html5up.net">HTML5 UP</a>'
hero_subtitle: 'Designed and built by <a href="http://twitter.com/ajlkn">AJ</a> and released for free under<br />the <a href="http://html5up.net/license">Creative Commons Attribution 3.0 license</a>.'
hero_button_text: 'Get this party started'
hero_button_url: '#'
blog-page: /blog
featuredposts: true
featuredposts_number: 3
social:
  -
    name: Facebook
    url: '#'
    icon: facebook
  -
    name: Twitter
    url: '#'
    icon: twitter
  -
    name: Instagram
    url: 'https://www.instagram.com'
    icon: instagram
  -
    name: Dribbble
    url: '#'
    icon: dribbble
  -
    name: Youtube
    url: '#'
    icon: youtube
  -
    name: Pinterest
    url: 'https://www.instagram.com'
    icon: pinterest
contact_title: null
contact_subtitle: null
copyright_author: 'Design: <a href="http://telephasic.juanvillen.es">Pedro Moreno</a>'
copyright_rights: '&copy; Pedro Moreno. All rights reserved.'
favicon:
  user/themes/telephasic/images/ico/favicon.png:
    name: favicon.png
    type: image/png
    size: 13203
    path: user/themes/telephasic/images/ico/favicon.png
social_enabled: true
featuredposts_category: featured
contact_enabled: true
